### ISSUE TITLE
Assistance Supporting Additional Resources

### ISSUE THREAD

**Issue by aj-foster** [antonbabenko/terraform-cost-estimation#12]
Hello there 👋 

Thank you for your work on this project! I'm curious about the best way for folks to contribute to the process of supporting new resources. For example, if I were interested in adding support for, say, Amazon RDS, how could I jump in?

Thank you!

**Comment by antonbabenko** [comment]
Hi AJ,

Right after I released this one, my priorities have shifted to open-sourcing https://serverless.tf framework, which is also used on the backend of https://terraform-cost-estimation.com/ service.

Saying this, I have not developed an easy interface for external developers to plug new resources, yet. I should come back to this project after the summer break, and simplify support for more resources.

Let's keep this issue open as a reminder for myself.

**Comment by aj-foster** [comment]
Closing as my own priorities have shifted.
