### ISSUE TITLE
feat: support for GCP

### ISSUE THREAD

**Issue by greenozon** [antonbabenko/terraform-cost-estimation#20]
Are there any plans to add support for GCP?
in 3 years it has added already the Pricing API, eg: 

[https://cloud.google.com/billing/docs/reference/pricing-api/rest](https://www.google.com/url?q=https://cloud.google.com/billing/docs/reference/pricing-api/rest&sa=D&source=calendar&usd=2&usg=AOvVaw0cOvhM-b48phVvSkiBycg7)

**Pricing API** 
Use the Cloud Billing Pricing API to get pricing information about all Google Cloud Services. If you have a custom pricing contract with Google Cloud, you can also use the API to get information about your contract prices.

@antonbabenko  what would be the recommended starting point to start working on the PR for this great goal?
thanks

**Comment by antonbabenko** [comment]
Hi Alex! There are no plans to add anything to this project. Consider exploring and contributing to @infracost if you are interested.
