### ISSUE TITLE
jq processing Error

### ISSUE THREAD

**Issue by maxtacu** [antonbabenko/terraform-cost-estimation#5]
Getting this error while trying to process the Terraform state or plan file with [terraform.jq](https://github.com/antonbabenko/terraform-cost-estimation/blob/master/terraform.jq) file:
```
$ terraform state pull | jq -cf terraform.jq 
jq: error: ARGS/0 is not defined at <top-level>, line 518:
, if $ARGS.named.extra != null then     
jq: error: walk/1 is not defined at <top-level>, line 24:
        walk(if isidle then . elif isiterable then delpaths([paths(isidle)]) else . end);        
jq: error: ENV/0 is not defined at <top-level>, line 43:
        fallback_region: ($ENV.AWS_DEFAULT_REGION // $ENV.AWS_REGION // "eu-west-1")                          
jq: error: ENV/0 is not defined at <top-level>, line 43:
        fallback_region: ($ENV.AWS_DEFAULT_REGION // $ENV.AWS_REGION // "eu-west-1")                                                     
jq: 4 compile errors
```
a workaround is to delete [this block](https://github.com/antonbabenko/terraform-cost-estimation/blob/9e558ff7ae899e934e3179edfb328ae01f049607/terraform.jq#L516-L522) from the [terraform.jq](https://github.com/antonbabenko/terraform-cost-estimation/blob/master/terraform.jq) file.

jq latest **1.5 version**
Terraform **v0.12.19**

**Comment by antonbabenko** [comment]
Hi @tmxak !

JQ version 1.6 is required for this to work.

https://github.com/stedolan/jq/releases

**Comment by antonbabenko** [comment]
Please give it a try and comment back if the problem persists.

**Comment by maxtacu** [comment]
yeah. you're right. works fine with **1.6** jq version. Apparently I accidentally skipped the **jq** version specs in the docs.
For installing jq I was following the [official docs](https://stedolan.github.io/jq/download/) for ubuntu. Didn't notice that there is a higher version.. Thanks @antonbabenko

**Comment by antonbabenko** [comment]
There is a note that JQ 1.6 is required in the doc, but I will make it a bit bigger to make sure that people use it.

Thanks for feedback!
